# Generated by Django 4.1.6 on 2023-02-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_teacher_name_teacher_subject_teacher_surname'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('title', 'course')},
        ),
    ]
