# Generated by Django 4.1.6 on 2023-02-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_group_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth')]),
        ),
    ]
