# Generated by Django 4.1.6 on 2023-02-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_group_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('tel_number', models.SlugField(max_length=11)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.teacher')),
            ],
        ),
    ]
