# Generated by Django 4.1.6 on 2023-03-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(related_name='teachers', to='base.group'),
        ),
    ]
