# Generated by Django 4.1.6 on 2023-03-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_teacher_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='easy@mail.ru', max_length=254),
            preserve_default=False,
        ),
    ]
